version: 2
jobs:
  build:
    docker:
      - image: kkarczmarczyk/node-yarn:8.0
      - image: redis:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
