version: 2
jobs:
  test:
    docker:
      - image: jonbaldie/yarn
    steps:
      - checkout
      - run: yarn
      - run: yarn test
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
